// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using UnityEngine;

public class MonoSingleton<T> : MonoBehaviour where T : MonoSingleton<T> {
	private static T inst = null;
	public static T Instance() {
		if (inst == null) {
			inst = GameObject.FindObjectOfType<T>();
			if (inst == null) {
				_Create();
			}
		}

		return inst;
	}

	private static T _Create() {
		try {
			Transform trans = new GameObject(typeof(T).Name).transform;
			trans.localScale = Vector3.zero;
			trans.localPosition = Vector3.zero;
			trans.localRotation = Quaternion.identity;

			inst = trans.gameObject.AddComponent<T>();
		}
		catch (Exception e) {
			Log.Exception(e);
			inst = null;
		}
		return inst;
	}
}


